FROM mcr.microsoft.com/mssql/server:2019-latest

# Switch to root user for access to set helpful aliases
USER root

RUN apt-get -y update && apt-get install -y vim unzip

RUN wget -q -O sqlpackage.zip https://aka.ms/sqlpackage-linux \
    && unzip -qq sqlpackage.zip -d /opt/mssql-tools/sqlpackage \
    && chmod +x /opt/mssql-tools/sqlpackage/sqlpackage \
    && rm sqlpackage.zip

# Helpful aliases
RUN echo 'alias ll='"'"'ls $LS_OPTIONS -al'"'"'' >> /etc/bash.bashrc 

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy Files
COPY ./database/*.sh ./database/*.sql /usr/src/app/
COPY ./sample_data/*.csv /usr/src/app/
COPY ./sample_data/*.fmt /usr/src/app/

# Grant permissions for the import-data script to be executable
RUN chmod 666 /usr/src/app/*.csv
RUN chmod +x /usr/src/app/import-data.sh
RUN chmod +x /usr/src/app/create_db_package.sh
RUN touch /usr/src/app/bcp_err.log
RUN chown -R mssql:root  /usr/src/app

# Switch back to mssql user and run the entrypoint script
USER mssql
ENTRYPOINT /bin/bash ./entrypoint.sh
